// Validates the examples in the documentation against the shipped schemas.
//
// The docs get regenerated by tooling that does not know what the schemas say,
// which is exactly how a config example ends up using keys that do not exist.
// A reader who copies a broken example has no way to tell it is broken.

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(ROOT, '..', '..', 'docs');
const SCHEMAS = path.join(ROOT, 'schemas');

const ajv = new Ajv({ allErrors: true, strict: false });

const lintSchema = JSON.parse(fs.readFileSync(path.join(SCHEMAS, 'glua.schema.json'), 'utf8'));
const fmtSchema = JSON.parse(fs.readFileSync(path.join(SCHEMAS, 'gluafmtrc.schema.json'), 'utf8'));

const validateLint = ajv.compile(lintSchema);
const validateFmt = ajv.compile(fmtSchema);

function mdxFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return mdxFiles(full);
    return entry.name.endsWith('.mdx') ? [full] : [];
  });
}

/** Fenced blocks, with the language and whatever title follows it. */
function codeBlocks(text) {
  const blocks = [];
  const re = /```(\w+)([^\n]*)\n([\s\S]*?)```/g;
  let match;
  while ((match = re.exec(text)) !== null) {
    const before = text.slice(0, match.index);
    blocks.push({
      language: match[1],
      title: match[2].trim(),
      body: match[3],
      line: before.split('\n').length,
    });
  }
  return blocks;
}

/** Strips comments and trailing commas, matching what the loader accepts. */
function parseLoose(text) {
  return JSON.parse(
    text
      .replace(/^\s*\/\/.*$/gm, '')
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/,(\s*[}\]])/g, '$1'),
  );
}

const files = mdxFiles(DOCS);

test('the documentation has pages to check', () => {
  assert.ok(files.length > 0, `no .mdx files found under ${DOCS}`);
});

/**
 * Generated configs point `$schema` at https://glua.bluejutzu.dev/schemas/,
 * which Mintlify serves straight from docs/schemas. Nothing rebuilds that
 * copy automatically, so a schema change here would otherwise ship silently
 * out of sync with what the hosted URL actually returns.
 */
test('docs/schemas is the same as the schemas we ship', () => {
  const DOCS_SCHEMAS = path.join(DOCS, 'schemas');
  for (const name of fs.readdirSync(SCHEMAS)) {
    const shipped = fs.readFileSync(path.join(SCHEMAS, name), 'utf8');
    const hosted = fs.readFileSync(path.join(DOCS_SCHEMAS, name), 'utf8');
    assert.equal(hosted, shipped, `docs/schemas/${name} is out of date — copy it from packages/glua-lsp/schemas`);
  }
});

test('every JSON example parses', () => {
  const failures = [];
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8');
    for (const block of codeBlocks(text)) {
      if (!['json', 'jsonc'].includes(block.language)) continue;
      try {
        parseLoose(block.body);
      } catch (error) {
        failures.push(
          `${path.relative(DOCS, file)}:${block.line} — ${error.message}`,
        );
      }
    }
  }
  assert.deepEqual(failures, []);
});

/** Which schema, if any, a block claims to be an example of. */
function schemaFor(file, block) {
  const hint = `${block.title} ${block.body.slice(0, 200)}`;
  if (/gluafmtrc/.test(hint)) return 'fmt';
  if (/\.glua\.json|glua\.schema/.test(hint)) return 'lint';

  // Untitled blocks on a page that is clearly about one of the two files.
  const page = path.relative(DOCS, file).replace(/\\/g, '/');
  if (page.includes('formatter')) return 'fmt';
  if (page.includes('rules')) return 'lint';
  return null;
}

test('config examples validate against the shipped schemas', () => {
  const failures = [];

  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8');
    for (const block of codeBlocks(text)) {
      if (!['json', 'jsonc'].includes(block.language)) continue;

      const which = schemaFor(file, block);
      if (!which) continue;

      let value;
      try {
        value = parseLoose(block.body);
      } catch {
        continue; // reported by the parse test
      }
      // Skip fragments that are plainly VS Code settings, not a config file.
      if (value && typeof value === 'object' && Object.keys(value).some((k) => k.startsWith('['))) {
        continue;
      }

      const validate = which === 'fmt' ? validateFmt : validateLint;
      if (validate(value)) continue;

      const problems = (validate.errors ?? [])
        .map((e) => `${e.instancePath || '/'} ${e.message}`)
        .join('; ');
      failures.push(
        `${path.relative(DOCS, file)}:${block.line} (${which}) — ${problems}`,
      );
    }
  }

  assert.deepEqual(failures, [], `\n${failures.join('\n')}\n`);
});

test('documented settings keys all exist in the manifest', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const known = new Set(
    Object.keys(manifest.contributes.configuration.properties).map((k) => k.replace(/^glua\./, '')),
  );

  const failures = [];
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8');
    // `glua.something.other` written inline in prose or a table.
    for (const match of text.matchAll(/`glua\.([a-zA-Z.]+)`/g)) {
      const key = match[1].replace(/\.$/, '');
      if (known.has(key)) continue;
      const line = text.slice(0, match.index).split('\n').length;
      failures.push(`${path.relative(DOCS, file)}:${line} — unknown setting glua.${key}`);
    }
  }

  assert.deepEqual(failures, [], `\n${failures.join('\n')}\n`);
});

test('documented diagnostic codes all exist', () => {
  const source = fs.readFileSync(
    path.join(ROOT, 'src', 'server', 'features', 'diagnostics.ts'),
    'utf8',
  );
  const codes = new Set(
    [...source.matchAll(/= '([a-z][a-z-]+)',/g)].map((m) => m[1]),
  );
  assert.ok(codes.size > 10, 'failed to read the diagnostic codes');

  const failures = [];
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8');
    // Codes appear in suppression examples: `-- glua-ignore some-code`
    // Only same-line whitespace: a bare `-- glua-ignore` must not swallow the
    // first word of the line it applies to.
    for (const match of text.matchAll(
      /glua-(?:ignore|disable(?:-line|-file)?|enable)[ \t]+([A-Za-z][A-Za-z-]+)/g,
    )) {
      const code = match[1];
      if (codes.has(code)) continue;
      // A plain lowercase word is prose, which a bare directive supports:
      // `-- glua-ignore because this stub is filled in later`. A hyphen or an
      // inner capital means someone was aiming at a rule name — the same test
      // parseRules applies — so a settings key written where a code belongs is
      // still reported rather than read as an explanation.
      if (!/[-A-Z]/.test(code.slice(1))) continue;
      const line = text.slice(0, match.index).split('\n').length;
      failures.push(`${path.relative(DOCS, file)}:${line} — unknown diagnostic code '${code}'`);
    }
  }

  assert.deepEqual(failures, [], `\n${failures.join('\n')}\n`);
});

/**
 * Every diagnostic carries a `codeDescription.href` pointing at its section on
 * the rules page. Nothing at runtime can tell whether that section exists, so
 * the link either lands on an explanation or scrolls to the top of a long page
 * and looks answered. These three assertions are what keep it honest.
 */
test('every rule has a catalogue entry and a section to link to', () => {
  const diagnostics = fs.readFileSync(
    path.join(ROOT, 'src', 'server', 'features', 'diagnostics.ts'),
    'utf8',
  );
  const codes = [...diagnostics.matchAll(/= '([a-z][a-z-]+)',/g)].map((m) => m[1]);
  assert.ok(codes.length > 10, 'failed to read the diagnostic codes');

  const catalogue = fs.readFileSync(path.join(ROOT, 'src', 'rules.ts'), 'utf8');
  const listed = [...catalogue.matchAll(/code: '([a-z][a-z-]+)'/g)].map((m) => m[1]);

  const page = fs.readFileSync(path.join(DOCS, 'reference', 'rules.mdx'), 'utf8');
  // The anchor Mintlify generates for `### \`some-code\`` is `some-code`.
  const sections = [...page.matchAll(/^#{2,3} `([a-z][a-z-]+)`\s*$/gm)].map((m) => m[1]);

  assert.deepEqual(
    codes.filter((code) => !listed.includes(code)),
    [],
    'diagnostic codes with no entry in src/rules.ts',
  );
  assert.deepEqual(
    listed.filter((code) => !codes.includes(code)),
    [],
    'catalogue entries for codes nothing reports',
  );
  assert.deepEqual(
    listed.filter((code) => !sections.includes(code)),
    [],
    'rules with no section on docs/reference/rules.mdx to link to',
  );
});

test('every settings key in the catalogue exists in the manifest', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const known = new Set(
    Object.keys(manifest.contributes.configuration.properties)
      .filter((key) => key.startsWith('glua.diagnostics.'))
      .map((key) => key.slice('glua.diagnostics.'.length)),
  );

  const catalogue = fs.readFileSync(path.join(ROOT, 'src', 'rules.ts'), 'utf8');
  const unknown = [...catalogue.matchAll(/settingsKey: '([a-zA-Z]+)'/g)]
    .map((m) => m[1])
    .filter((key) => !known.has(key));

  assert.deepEqual(unknown, [], 'settings keys the extension does not contribute');
});
